services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - planning_applications_data:/var/lib/postgresql/data
    hostname: postgres
    container_name: database

  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scrapy
    env_file:
      - .env
    links:
      - db
    volumes:
      - ./output:/app/output

volumes:
  planning_applications_data:
